travis:
  alt_text:   Build Status
  scheme:     https
  url_path:   travis-ci.org
  offers_svg: true

coveralls:
  alt_text:   Coverage Status
  url_path:   coveralls.io/r
  badge_slug: coveralls

gemnasium:
  alt_text:   Dependency Status
  url_path:   gemnasium.com
  badge_slug: gemnasium

codeclimate:
  alt_text:   Code Climate
  url_path:   codeclimate.com/github
  badge_slug: codeclimate/github
