services:
  defaults:
    travis:
      alt_text:   Build Status
      url:        travis-ci.org
      badge_slug: travis

    coveralls:
      alt_text:   Coverage Status
      url:        coveralls.io/r
      badge_slug: coveralls

    gemnasium:
      alt_text:   Dependency Status
      url:        gemnasium.com
      badge_slug: gemnasium

    codeclimate:
      alt_text:   Code Climate
      url:        codeclimate.com/github
      badge_slug: codeclimate/github

  extras:
    mit:
      alt_text:   License
      badge_path: ":license-mit-blue.svg"
      url:        http://%s.mit-license.org

  licenses:
    mit:
      url:        http://%s.mit-license.org

    apache:
      url:        http://www.apache.org/licenses/LICENSE-2.0.html

    gpl2:
      url:        http://www.gnu.org/licenses/gpl-2.0.html

    gpl3:
      url:        http://www.gnu.org/licenses/gpl-3.0.html

badge_service:    img.shields.io